export const languageCodes = {
  Afrikaans: "afr",
  Amharic: "amh",
  Arabic: "ara",
  Assamese: "asm",
  Azerbaijani: "aze",
  "Azerbaijani - Cyrillic": "aze_cyrl",
  Belarusian: "bel",
  Bengali: "ben",
  Tibetan: "bod",
  Bosnian: "bos",
  Bulgarian: "bul",
  Catalan: "cat",
  Cebuano: "ceb",
  Cherokee: "chr",
  "Chinese - Simplified": "chi_sim",
  "Chinese - Traditional": "chi_tra",
  Corsican: "cos",
  Croatian: "hrv",
  Czech: "ces",
  Danish: "dan",
  Divehi: "div",
  Dutch: "nld",
  English: "eng",
  Estonian: "est",
  Fijian: "fij",
  Finnish: "fin",
  French: "fra",
  Galician: "glg",
  Georgian: "kat",
  German: "deu",
  Greek: "ell",
  Gujarati: "guj",
  "Haitian - Creole": "hat",
  Hebrew: "heb",
  Hindi: "hin",
  Hungarian: "hun",
  Icelandic: "isl",
  Indonesian: "ind",
  Italian: "ita",
  Japanese: "jpn",
  Javanese: "jav",
  Kannada: "kan",
  Kazakh: "kaz",
  Khmer: "khm",
  Korean: "kor",
  Kurdish: "kur",
  Kyrgyz: "kir",
  Lao: "lao",
  Latin: "lat",
  Latvian: "lav",
  Lithuanian: "lit",
  Malayalam: "mal",
  Maltese: "mlt",
  Maori: "mri",
  Marathi: "mar",
  Mongolian: "mon",
  Nepali: "nep",
  Norwegian: "nor",
  Oriya: "ori",
  Panjabi: "pan",
  Persian: "fas",
  Polish: "pol",
  Portuguese: "por",
  Pushto: "pus",
  Quechua: "que",
  Romanian: "ron",
  Russian: "rus",
  "Serbian - Latin": "srp_latn",
  "Serbian - Cyrillic": "srp_cyrl",
  Sinhala: "sin",
  Slovak: "slk",
  Slovenian: "slv",
  Spanish: "spa",
  Sundanese: "sun",
  Swahili: "swa",
  Swedish: "swe",
  Tagalog: "tgl",
  Tajik: "tgk",
  Tamil: "tam",
  Telugu: "tel",
  Thai: "tha",
  Tibetan: "bod",
  Turkish: "tur",
  Ukrainian: "ukr",
  Urdu: "urd",
  Uzbek: "uzb",
  "Uzbek - Cyrillic": "uzb_cyrl",
  Vietnamese: "vie",
  Welsh: "cym",
  Yiddish: "yid",
};
